name: Tests and Benchmarks

on:
  - push
  - workflow_dispatch

jobs:
#  tests:
    #runs-on: ubuntu-latest
    #steps:
     # - name: Checkout
       #  uses: actions/checkout@v4
#      - name: Install Go
#         uses: actions/setup-go@v5
  #       with:
    #       go-version: "1.22"
      #     check-latest: true
        #   cache: true
#       - name: Run Tests
#         run: go test -v ./...
#   tests-race:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Install Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: "1.22"
#           check-latest: true
#           cache: true
#       - name: Test with Race Conditions
#         run: go test -race -v ./...
#         timeout-minutes: 15
  benchmarks:
    runs-on: architect-template-KAGECqUj
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: true
      - name: Benchmark
        run: go test -run=^$ -bench=. -v ./...
#   benchmarks-race:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout
#         uses: actions/checkout@v4
#       - name: Install Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: "1.22"
#           check-latest: true
#           cache: true
#       - name: Benchmark with Race Conditions
#         run: go test -run=^$ -bench=. -race -timeout 30m -v ./...
#         timeout-minutes: 30
